version: "3"
services:
  hub:
    image: selenium/hub:latest
    restart: always
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      NODE_MAX_INSTANCES: 10
      NODE_MAX_SESSION: 10
      HUB_HOST: hub
    restart: always