version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  selenium-project:
    image: sritaj/selenium_docker:48
    depends_on:
      - chrome
      - firefox
    environment:
      - GRIDRUN=Yes
      - BROWSER=Chrome
      - HUB_HOST=hub
      - MODULE=flight-details-test.xml
    volumes:
      - /Users/sritaj/Technical KnowHow/SeleniumProjects/output:/usr/share/udemy/test-output
